export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE'

export const SET_LANG = 'SET_LANG'
export const SET_PAGE = 'SET_PAGE'
export const REQUEST_PAGES = 'REQUEST_PAGES'
export const RECEIVE_PAGES = 'RECEIVE_PAGES'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'

export const REQUEST_GS = 'REQUEST_GS'
export const RECEIVE_GS = 'RECEIVE_GS'

export const DETAIL_MODAL = 'DETAIL_MODAL'

export const RECEIVE_MANIFEST = 'RECEIVE_MANIFEST'
export const REQUEST_MANIFEST = 'REQUEST_MANIFEST'
export const NULLIFY_IIIF = 'NULLIFY_IIIF'
export const RECEIVE_IIIF = 'RECEIVE_IIIF'
export const REQUEST_IIIF = 'REQUEST_IIIF'

export const REQUEST_ES_DATA = 'REQUEST_ES_DATA'
export const RECEIVE_ES_DATA = 'RECEIVE_ES_DATA'
export const RECEIVE_DATA = 'RECEIVE_DATA'
export const REQUEST_DATA = 'REQUEST_DATA'
export const REQUEST_WORKS = 'REQUEST_WORKS'
export const RECEIVE_WORKS = 'RECEIVE_WORKS'

export const REQUEST_ID = 'REQUEST_ID'
export const RECEIVE_ID = 'RECEIVE_ID'

export const RECEIVE_AUTHORS = 'RECEIVE_AUTHORS'
export const REQUEST_AUTHORS = 'REQUEST_AUTHORS'

export const RECEIVE_TOPICS = 'RECEIVE_TOPICS'
export const REQUEST_TOPICS = 'REQUEST_TOPICS'

export const RECEIVE_SUBJECTS = 'RECEIVE_SUBJECTS'
export const REQUEST_SUBJECTS = 'REQUEST_SUBJECTS'

export const REQUEST_RESOURCES = 'REQUEST_RESOURCES'
export const RECEIVE_RESOURCES = 'RECEIVE_RESOURCES'

export const SET_COLLAPSE = 'SET_COLLAPSE'
export const SET_BROWSE = 'SET_BROWSE'
export const SET_COLLECTION = 'SET_COLLECTION'