export const REQUEST_PAGES = 'REQUEST_PAGES'
export const RECEIVE_PAGES = 'RECEIVE_PAGES'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'

export const REQUEST_GS = 'REQUEST_GS'
export const RECEIVE_GS = 'RECEIVE_GS'

export const REQUEST_WORKS = 'REQUEST_WORKS'
export const RECEIVE_WORKS = 'RECEIVE_WORKS'
export const ERROR_ELASTIC = 'ERROR_ELASTIC'

export const REQUEST_ID = 'REQUEST_ID'
export const RECEIVE_ID = 'RECEIVE_ID'

export const RECEIVE_AUTHORS = 'RECEIVE_AUTHORS'
export const REQUEST_AUTHORS = 'REQUEST_AUTHORS'

export const RECEIVE_SUBJECTS = 'RECEIVE_SUBJECTS'
export const REQUEST_SUBJECTS = 'REQUEST_SUBJECTS'

export const REQUEST_ASSOCIATED_RECORDS = 'REQUEST_ASSOCIATED_RECORDS'
export const RECEIVE_ASSOCIATED_RECORDS = 'RECEIVE_ASSOCIATED_RECORDS'

export const REQUEST_COLLECTIONS = 'REQUEST_COLLECTIONS'
export const RECEIVE_COLLECTIONS = 'RECEIVE_COLLECTIONS'
export const ERROR_COLLECTIONS = 'ERROR_COLLECTIONS'
