export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE'

export const SET_LANG = 'SET_LANG'
export const SET_PAGE = 'SET_PAGE'
export const REQUEST_PAGES = 'REQUEST_PAGES'
export const RECEIVE_PAGES = 'RECEIVE_PAGES'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'

export const REQUEST_GS = 'REQUEST_GS'
export const RECEIVE_GS = 'RECEIVE_GS'

export const SET_MODAL = 'SET_MODAL'

export const REQUEST_WORKS = 'REQUEST_WORKS'
export const RECEIVE_WORKS = 'RECEIVE_WORKS'

export const REQUEST_ID = 'REQUEST_ID'
export const RECEIVE_ID = 'RECEIVE_ID'

export const RECEIVE_AUTHORS = 'RECEIVE_AUTHORS'
export const REQUEST_AUTHORS = 'REQUEST_AUTHORS'

export const RECEIVE_SUBJECTS = 'RECEIVE_SUBJECTS'
export const REQUEST_SUBJECTS = 'REQUEST_SUBJECTS'

export const REQUEST_ASSOCIATED_RECORDS = 'REQUEST_ASSOCIATED_RECORDS'
export const RECEIVE_ASSOCIATED_RECORDS = 'RECEIVE_ASSOCIATED_RECORDS'

export const SET_COLLAPSE = 'SET_COLLAPSE'
export const SET_BROWSE = 'SET_BROWSE'
export const SET_COLLECTION = 'SET_COLLECTION'

export const REQUEST_COLLECTIONS = 'REQUEST_COLLECTIONS'
export const RECEIVE_COLLECTIONS = 'RECEIVE_COLLECTIONS'
export const ERROR_COLLECTIONS = 'ERROR_COLLECTIONS'
